//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBff.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileBff.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Account_Details {
            get {
                return ResourceManager.GetString("Account_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountItem_AccountName {
            get {
                return ResourceManager.GetString("AccountItem_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string AccountItem_AccountNumber {
            get {
                return ResourceManager.GetString("AccountItem_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account owner.
        /// </summary>
        public static string AccountItem_AccountOwner {
            get {
                return ResourceManager.GetString("AccountItem_AccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string AccountItem_AccountType {
            get {
                return ResourceManager.GetString("AccountItem_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank giro.
        /// </summary>
        public static string AccountItem_BankGiro {
            get {
                return ResourceManager.GetString("AccountItem_BankGiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swish corporate.
        /// </summary>
        public static string AccountItem_SwishCorporate {
            get {
                return ResourceManager.GetString("AccountItem_SwishCorporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swish for merchants.
        /// </summary>
        public static string AccountItem_SwishForMerchants {
            get {
                return ResourceManager.GetString("AccountItem_SwishForMerchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-invoice.
        /// </summary>
        public static string FutureEventDetailType_EInvoice {
            get {
                return ResourceManager.GetString("FutureEventDetailType_EInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string FutureEventDetailType_Fee {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string FutureEventDetailType_Incomming {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Incomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International payment.
        /// </summary>
        public static string FutureEventDetailType_InternationalPayment {
            get {
                return ResourceManager.GetString("FutureEventDetailType_InternationalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan payment.
        /// </summary>
        public static string FutureEventDetailType_LoanPayment {
            get {
                return ResourceManager.GetString("FutureEventDetailType_LoanPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string FutureEventDetailType_Other {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string FutureEventDetailType_Payment {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing new event.
        /// </summary>
        public static string FutureEventDetailType_ProcessingNewEvent {
            get {
                return ResourceManager.GetString("FutureEventDetailType_ProcessingNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring transfer.
        /// </summary>
        public static string FutureEventDetailType_RecurringTransfer {
            get {
                return ResourceManager.GetString("FutureEventDetailType_RecurringTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string FutureEventDetailType_Salary {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string FutureEventDetailType_Transfer {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FutureEventDetailType_Unknown {
            get {
                return ResourceManager.GetString("FutureEventDetailType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankgiro deposit.
        /// </summary>
        public static string TransactionType_BankgiroDeposit {
            get {
                return ResourceManager.GetString("TransactionType_BankgiroDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card transaction.
        /// </summary>
        public static string TransactionType_CardTransaction {
            get {
                return ResourceManager.GetString("TransactionType_CardTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International payment.
        /// </summary>
        public static string TransactionType_InternationalPayment {
            get {
                return ResourceManager.GetString("TransactionType_InternationalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string TransactionType_Other {
            get {
                return ResourceManager.GetString("TransactionType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string TransactionType_Payment {
            get {
                return ResourceManager.GetString("TransactionType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring transfer.
        /// </summary>
        public static string TransactionType_RecurringTransfer {
            get {
                return ResourceManager.GetString("TransactionType_RecurringTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swish payment.
        /// </summary>
        public static string TransactionType_SwishPayment {
            get {
                return ResourceManager.GetString("TransactionType_SwishPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TransactionType_Transfer {
            get {
                return ResourceManager.GetString("TransactionType_Transfer", resourceCulture);
            }
        }
    }
}
