apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ASPNETCORE_ENVIRONMENT":"Development"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"ap-bff-mobile-apps","namespace":"ap-bff-mobile-apps"}}
  name: ap-bff-mobile-apps
  namespace: ap-bff-mobile-apps
